SELECT 
    TOTAL_RECORDS,
    NON_NULL_DAYS_SUPPLY,
    NON_NULL_PATIENT_AGE,
    NON_NULL_FILL_STATUS,
    NON_NULL_NDC_MATCHES
FROM PL_APP_RPHAI.RAW_RPHAI.NBA5_WITH_DRUG_DEBUG
LIMIT 1;

SELECT 
    TOTAL_RECORDS_AFTER_DC,
    NON_NULL_DAYS_SUPPLY_AFTER_DC,
    NON_NULL_PATIENT_AGE_AFTER_DC,
    NON_NULL_FILL_STATUS_AFTER_DC,
    NON_NULL_DC_MATCHES
FROM PL_APP_RPHAI.RAW_RPHAI.NBA5_WITH_DRUG_FINAL_DEBUG
LIMIT 1;
